INSERT INTO Cities (CityName, CountryCode) VALUES ('Makati City', 162);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Mandaluyong City', 162);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Pasay City', 162);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Pasig City', 162);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Quezon City', 162);
INSERT INTO Cities (CityName, CountryCode) VALUES ('San Juan City', 162);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Santa Rosa', 162);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Tagaytay City', 162);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Taguig City', 162);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Bras�_lia', 30);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Rio de Janeiro', 30);
INSERT INTO Cities (CityName, CountryCode) VALUES ('S��o Paulo', 30);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Albany', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Armidale', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Athens', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Augusta', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Balingup', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Beechworth', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Boise', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Cedar Rapids/Iowa City', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Chatham-Kent', 37);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Clatskanie', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Cochrane', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Columbus', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Consort', 37);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Dalton', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Davenport', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Des Moines', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Dicky Beach', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Dubuque', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('East Ballina', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Fernley', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Flaxton', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Forrest', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Gainesville', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Hepburn Springs', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Huskisson', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Inverloch', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Lakes Entrance', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Lakeview', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Lincoln', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Lorn', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Macedon', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Macon', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Mayfield', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Mc Millan', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Middleton Beach', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Miller', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Monroe', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Montville', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Ojo Caliente', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Orlando', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Palm Cove', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Paynesville', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Penola', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Pensacola', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Phillip Island', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Pocatello', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Potrero', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Princeton', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Rest of Hawaii', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Savannah', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Singapore', 184);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Sioux City', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Tampa Bay', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Tanunda', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Trentham East', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Valdosta', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Vernonia', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Victor Harbor', 14);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Vineland Station', 37);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Waterloo', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Weirton', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Winchester Bay', 216);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Yorkton', 37);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Abu Dhabi', 214);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Dubai', 214);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Sharjah', 214);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Agra', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Ahmedabad', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Allahabad', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Amritsar', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Aurangabad', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Bangalore', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Bhopal', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Bhubaneshwar', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Chandigarh', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Chennai', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Coimbatore', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Dehradun', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Faridabad', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Ghaziabad', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Goa', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Gurgaon', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Guwahati', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Hyderabad', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Indore', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Jaipur', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Kanpur', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Kochi', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Kolkata', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Lucknow', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Ludhiana', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Mangalore', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Mohali', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Mumbai', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Mysore', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Nagpur', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Nashik', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('New Delhi', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Noida', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Panchkula', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Patna', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Puducherry', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Pune', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Ranchi', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Secunderabad', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Surat', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Vadodara', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Varanasi', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Vizag', 1);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Bandung', 94);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Bogor', 94);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Jakarta', 94);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Tangerang', 94);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Auckland', 148);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Wellington City', 148);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Birmingham', 215);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Edinburgh', 215);
INSERT INTO Cities (CityName, CountryCode) VALUES ('London', 215);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Manchester', 215);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Doha', 166);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Cape Town', 189);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Inner City', 189);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Johannesburg', 189);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Pretoria', 189);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Randburg', 189);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Sandton', 189);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Colombo', 191);
INSERT INTO Cities (CityName, CountryCode) VALUES ('Ankara', 208);
INSERT INTO Cities (CityName, CountryCode) VALUES ('��stanbul', 208);