INSERT INTO Countries (CountryCode, CountryName) VALUES (162, 'Philippines');
INSERT INTO Countries (CountryCode, CountryName) VALUES (30, 'Brazil');
INSERT INTO Countries (CountryCode, CountryName) VALUES (216, 'United States');
INSERT INTO Countries (CountryCode, CountryName) VALUES (14, 'Australia');
INSERT INTO Countries (CountryCode, CountryName) VALUES (37, 'Canada');
INSERT INTO Countries (CountryCode, CountryName) VALUES (184, 'Singapore');
INSERT INTO Countries (CountryCode, CountryName) VALUES (214, 'United Arab Emirates');
INSERT INTO Countries (CountryCode, CountryName) VALUES (1, 'India');
INSERT INTO Countries (CountryCode, CountryName) VALUES (94, 'Indonesia');
INSERT INTO Countries (CountryCode, CountryName) VALUES (148, 'New Zealand');
INSERT INTO Countries (CountryCode, CountryName) VALUES (215, 'United Kingdom');
INSERT INTO Countries (CountryCode, CountryName) VALUES (166, 'Qatar');
INSERT INTO Countries (CountryCode, CountryName) VALUES (189, 'South Africa');
INSERT INTO Countries (CountryCode, CountryName) VALUES (191, 'Sri Lanka');
INSERT INTO Countries (CountryCode, CountryName) VALUES (208, 'Turkey');