INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (1, 'French');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (2, 'Japanese');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (3, 'Desserts');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (4, 'Seafood');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (5, 'Asian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (6, 'Filipino');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (7, 'Indian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (8, 'Sushi');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (9, 'Korean');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (10, 'Chinese');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (11, 'European');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (12, 'Mexican');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (13, 'American');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (14, 'Ice Cream');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (15, 'Cafe');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (16, 'Italian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (17, 'Pizza');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (18, 'Bakery');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (19, 'Mediterranean');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (20, 'Fast Food');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (21, 'Brazilian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (22, 'Arabian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (23, 'Bar Food');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (24, 'Grill');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (25, 'International');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (26, 'Peruvian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (27, 'Latin American');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (28, 'Burger');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (29, 'Juices');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (30, 'Healthy Food');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (31, 'Beverages');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (32, 'Lebanese');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (33, 'Sandwich');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (34, 'Steak');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (35, 'BBQ');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (36, 'Gourmet Fast Food');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (37, 'Mineira');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (38, 'North Eastern');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (39, 'Coffee and Tea');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (40, 'Vegetarian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (41, 'Tapas');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (42, 'Breakfast');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (43, 'Diner');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (44, 'Southern');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (45, 'Southwestern');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (46, 'Spanish');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (47, 'Argentine');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (48, 'Caribbean');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (49, 'German');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (50, 'Vietnamese');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (51, 'Thai');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (52, 'Modern Australian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (53, 'Teriyaki');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (54, 'Cajun');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (55, 'Canadian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (56, 'Tex-Mex');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (57, 'Middle Eastern');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (58, 'Greek');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (59, 'Bubble Tea');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (60, 'Tea');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (61, 'Australian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (62, 'Fusion');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (63, 'Cuban');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (64, 'Hawaiian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (65, 'Salad');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (66, 'Irish');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (67, 'New American');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (68, 'Soul Food');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (69, 'Turkish');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (70, 'Pub Food');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (71, 'Persian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (72, 'Continental');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (73, 'Singaporean');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (74, 'Malay');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (75, 'Cantonese');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (76, 'Dim Sum');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (77, 'Western');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (78, 'Finger Food');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (79, 'British');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (80, 'Deli');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (81, 'Indonesian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (82, 'North Indian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (83, 'Mughlai');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (84, 'Biryani');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (85, 'South Indian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (86, 'Pakistani');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (87, 'Afghani');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (88, 'Hyderabadi');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (89, 'Rajasthani');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (90, 'Street Food');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (91, 'Goan');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (92, 'African');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (93, 'Portuguese');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (94, 'Gujarati');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (95, 'Armenian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (96, 'Mithai');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (97, 'Maharashtrian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (98, 'Modern Indian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (99, 'Charcoal Grill');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (100, 'Malaysian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (101, 'Burmese');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (102, 'Chettinad');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (103, 'Parsi');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (104, 'Tibetan');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (105, 'Raw Meats');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (106, 'Kerala');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (107, 'Belgian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (108, 'Kashmiri');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (109, 'South American');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (110, 'Bengali');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (111, 'Iranian');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (112, 'Lucknowi');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (113, 'Awadhi');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (114, 'Nepalese');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (115, 'Drinks Only');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (116, 'Oriya');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (117, 'Bihari');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (118, 'Assamese');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (119, 'Andhra');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (120, 'Mangalorean');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (121, 'Malwani');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (122, 'Cuisine Varies');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (123, 'Moroccan');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (124, 'Naga');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (125, 'Sri Lankan');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (126, 'Peranakan');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (127, 'Sunda');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (128, 'Ramen');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (129, 'Kiwi');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (130, 'Asian Fusion');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (131, 'Taiwanese');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (132, 'Fish and Chips');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (133, 'Contemporary');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (134, 'Scottish');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (135, 'Curry');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (136, 'Patisserie');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (137, 'South African');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (138, 'Durban');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (139, 'Kebab');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (140, 'Turkish Pizza');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (141, 'Izgara');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (142, 'World Cuisine');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (143, 'Doner');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (144, 'Restaurant Cafe');
INSERT INTO Cuisines (CuisineID, CuisineType) VALUES (145, 'Borek');